config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin, path: Spree.admin_path do
    resource :mail_method, only: [:edit, :update] do
      post :testmail, on: :collection
    end
  end
end

app/models/spree/app_configuration_decorator.rb
module Spree
  AppConfiguration.class_eval do
    # Default mail headers settings
    preference :mails_from, :string, default: 'spree@example.com'
    preference :enable_mail_delivery, :boolean, default: false
    preference :mail_bcc, :string, default: 'spree@example.com'
    preference :intercept_email, :string, default: nil

    # Default smtp settings
    preference :mail_host, :string, default: 'localhost'
    preference :mail_domain, :string, default: 'localhost'
    preference :mail_port, :integer, default: 25
    preference :secure_connection_type, :string, default: Core::MailSettings::SECURE_CONNECTION_TYPES[0]
    preference :mail_auth_type, :string, default: Core::MailSettings::MAIL_AUTH[0]
    preference :smtp_username, :string, default: nil
    preference :smtp_password, :string, default: nil

    def override_actionmailer_config
      raise 'override_actionmailer_config has been removed. ' \
            'actionmailer\'s config is always overwridden when spree_mail_settings is included'
    end
    alias_method :override_actionmailer_config=, :override_actionmailer_config
  end
end

app/controllers/spree/admin/mail_methods_controller.rb
module Spree
  module Admin
    class MailMethodsController < BaseController
      def update
        params[:smtp_password] = nil if params[:smtp_username].blank?

        params.each do |name, value|
          next unless Spree::Config.has_preference? name
          Spree::Config[name] = value
        end

        flash[:success] = Spree.t(:successfully_updated, resource: Spree.t(:mail_method_settings))
        redirect_to edit_admin_mail_method_url
      end

      def testmail
        if TestMailer.test_email(try_spree_current_user.email).deliver_now
          flash[:success] = Spree.t('mail_methods.testmail.delivery_success')
        else
          flash[:error] = Spree.t('mail_methods.testmail.delivery_error')
        end
      rescue => e
        flash[:error] = Spree.t('mail_methods.testmail.error', e: e)
      ensure
        redirect_to edit_admin_mail_method_url
      end
    end
  end
end

app/views/spree/admin/mail_methods/_form.html.erb
<div data-hook="admin_mail_method_form_fields">
  <div class="row">

    <div class="col-md-6" data-hook="general">
      <fieldset>
        <legend><%= Spree.t(:general) %></legend>

        <div class="form-group">
          <div class="inline-radio">
            <%= label_tag :enable_mail_delivery do %>
              <%= preference_field_tag(:enable_mail_delivery, Spree::Config[:enable_mail_delivery], type: :boolean) %>
              <%= Spree.t(:enable_mail_delivery) %>
            <% end %>
          </div>
        </div>

        <div class="form-group">
          <%= label_tag :mails_from, Spree.t(:send_mails_as) %>
          <%= text_field_tag :mails_from, Spree::Config[:mails_from], maxlength: 256, class: 'form-control' %>
          <span class="info">
            <%= Spree.t(:smtp_send_all_emails_as_from_following_address) %>
          </span>
        </div>

        <div class="form-group">
          <%= label_tag :mail_bcc, Spree.t(:send_copy_of_all_mails_to) %>
          <%= text_field_tag :mail_bcc, Spree::Config[:mail_bcc], maxlength: 256, class: 'form-control' %>
          <span class="info">
            <%= Spree.t(:smtp_send_copy_to_this_addresses) %>
          </span>
        </div>

        <div class="form-group">
          <%= label_tag :intercept_email, Spree.t(:intercept_email_address) %>
          <%= text_field_tag :intercept_email, Spree::Config[:intercept_email], maxlength: 256, class: 'form-control' %>
          <span class="info">
            <%= Spree.t(:intercept_email_instructions) %>
          </span>
        </div>
      </fieldset>
    </div>

    <div class="col-md-6" data-hook="smtp">
      <fieldset>
        <legend><%= Spree.t(:smtp) %></legend>
        <div class="form-group">
          <%= label_tag :mail_domain, Spree.t(:smtp_domain) %>
          <%= text_field_tag :mail_domain, Spree::Config[:mail_domain], class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= label_tag :mail_host, Spree.t(:smtp_mail_host) %>
          <%= text_field_tag :mail_host, Spree::Config[:mail_host], class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= label_tag :mail_port, Spree.t(:smtp_port) %>
          <%= text_field_tag :mail_port, Spree::Config[:mail_port], class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= label_tag :secure_connection_type, Spree.t(:secure_connection_type) %>
          <%= select_tag(:secure_connection_type,
                         options_from_collection_for_select(Spree::Core::MailSettings::SECURE_CONNECTION_TYPES, :to_s, :to_s, Spree::Config[:secure_connection_type]),
                         class: 'select2') %>
        </div>
        <div class="form-group">
          <%= label_tag :mail_auth_type, Spree.t(:smtp_authentication_type) %>
          <%= select_tag(:mail_auth_type,
                         options_from_collection_for_select(Spree::Core::MailSettings::MAIL_AUTH, :to_s, :to_s, Spree::Config[:mail_auth_type]),
                         class: 'select2') %>
        </div>
        <div class="form-group">
          <%= label_tag :smtp_username, Spree.t(:smtp_username) %>
          <%= text_field_tag :smtp_username, Spree::Config[:smtp_username], class: 'form-control', autocomplete: 'off' %>
        </div>
        <div class="form-group">
          <%= label_tag :preferred_smtp_password, Spree.t(:smtp_password) %>
          <%= password_field_tag :smtp_password, Spree::Config[:smtp_password], class: 'form-control', autocomplete: 'off' %>
        </div>
      </fieldset>
    </div>
  </div>
</div>

app/views/spree/admin/mail_methods/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:mail_method_settings) %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'envelope', Spree.t('mail_methods.send_testmail'), testmail_admin_mail_method_path,
    method: :post, title: Spree.t('mail_methods.send_testmail'), class: 'send_mail btn btn-default' %>
<% end %>

<%= form_tag admin_mail_method_path, method: :put do |f| %>
  <fieldset>
    <%= render 'form', f: f %>
    <div class="form-actions actions" data-hook="buttons"><%= button Spree.t('actions.update'), 'update' %></div>
  </fieldset>
<% end %>